### ISSUE TITLE
QUESTION: when is extened rule -eX needed?

### ISSUE THREAD

**Issue by jobcespedes** [jhaws1982/rustycan4docker#5]
Hi,

I was wondering if cangw with -eX is generally needed or even when it is needed.

**Comment by jhaws1982** [comment]
The `-e` is for echo, the `-X` is for extended frames. I don't recall why the `-e` was used, maybe for additional vision when debugging and using candump (and could be leftover from the code this was based on). The `-X` is required if using extended CAN frames.

**Comment by jobcespedes** [comment]
Thank you. In some places I only saw `-e` being used. This is the first time I see `-X` I was wondering what the use case case was and if it was a general one.

**Comment by jhaws1982** [comment]
Yeah, the `-e` is just for when using normal CAN frames. The `-ex` was for when extended frames are needed. In many cases, both are enabled to allow any and all CAN traffic.

If this answers the question, feel free to close the ticket. Thanks!
